#version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./Postgres/volumes:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    image: findmyjob
    build:
      context: ./src/main/resources/app/Dockerfile .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres # jdbc:postgresql://localhost:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
